- packages/frontapp/src/app/components/BookInfo/index.tsx
- packages/frontapp/src/app/components/ErrorMessge/index.tsx
- packages/frontapp/src/app/pages/BookPreview.tsx
> edit functionality finished with modals

- packages/frontapp/src/app/components/Search/index.tsx
- packages/frontapp/src/app/pages/BookPreview.tsx
> fixed bug with taken items not being shown

- packages/apiserver/src/app/app.module.ts
- packages/apiserver/src/migrations/1657919176160-migrationMy.ts
- packages/apiserver/src/resources/item/item.resolver.ts
- packages/apiserver/src/resources/messages/message.entity.ts
- packages/apiserver/src/resources/messages/message.resolver.ts
- packages/apiserver/src/resources/messages/message.schema.graphql
- packages/apiserver/src/schema.graphql
- packages/apollo-client/src/graphql.schema.json
- packages/apollo-client/src/lib/generated/client-types.ts
- packages/apollo-client/src/lib/mutations/createMessageForManager.gql
- packages/apollo-client/src/lib/queries/getAllMessages.gql
- packages/frontapp/src/app/components/AskManagerForm/index.tsx
- packages/frontapp/src/app/components/ManagerInfoCard/index.tsx
- packages/frontapp/src/app/components/Notifications/index.tsx
- packages/frontapp/src/app/components/UserCard/index.tsx
- packages/frontapp/src/app/pages/NotificationPage.tsx
- packages/global-types/src/lib/global-types.ts
- packages/localization/src/lib/resources.ts
> [270] Managers notification list

- packages/frontapp/src/app/components/CategoriesList/index.tsx
- packages/frontapp/src/app/components/Modal/index.tsx
- packages/frontapp/src/app/components/Navbar/index.tsx
- packages/frontapp/src/app/components/Sidebar/index.tsx
modal is of normal height, menu closes on click on mobile phones
> bug fixes #273, #277

- packages/frontapp/src/app/components/Header/index.tsx
- packages/frontapp/src/app/components/NavbarItem/index.tsx
- packages/frontapp/src/app/components/Sidebar/index.tsx
https://user-images.githubusercontent.com/63979168/180775263-a8e4c812-ef77-45b0-a0e3-37ec9c977beb.MP4
> fixed bug #276

- packages/frontapp/src/app/app.tsx
- packages/frontapp/src/app/components/Scanner/index.tsx
- packages/frontapp/src/app/pages/SettingsPage.tsx
- packages/frontapp/src/app/store/slices/userSlice.ts
- packages/localization/src/lib/i18n.ts
- packages/localization/src/lib/resources.ts
> [302]: Change app language

- packages/apiserver/src/resources/item/item.resolver.ts
- packages/apiserver/src/resources/item/item.service.ts
- packages/apiserver/src/resources/item/item.shema.graphql
- packages/apollo-client/src/graphql.schema.json
- packages/apollo-client/src/lib/generated/client-types.ts
- packages/apollo-client/src/lib/queries/getItemsForClaimHistory.gql
- packages/frontapp/src/app/components/BookCard/index.tsx
- packages/frontapp/src/app/components/BookStatus/index.tsx
- packages/frontapp/src/app/pages/HistoryOfClaimPage.tsx
- packages/global-types/src/lib/global-types.ts
- packages/localization/src/lib/resources.ts
> [303] Claim history

- DEPLOY.md
- packages/apiserver/project.json
- packages/apollo-client/src/lib/generated/client-types.ts
- packages/apollo-client/src/lib/queries/getStatusesByMaterial.gql
- packages/frontapp/.storybook/main.js
- packages/frontapp/src/app/components/EmptyListItems/index.tsx
- packages/frontapp/src/app/components/InstructionsClaim/index.tsx
- packages/frontapp/src/app/components/Scanner/index.tsx
- packages/frontapp/src/app/components/Search/index.tsx
- packages/frontapp/src/app/components/UserList/SingleUser.tsx
- packages/frontapp/src/app/components/UserList/index.tsx
- packages/frontapp/src/app/globalUI/Table/index.tsx
- packages/frontapp/src/app/globalUI/TextArticle/index.tsx
- packages/frontapp/src/app/hooks/useDebounce.ts
- packages/frontapp/src/app/hooks/useRoutes.tsx
- packages/frontapp/src/app/pages/BookPreview.tsx
- packages/frontapp/src/app/pages/HistoryOfClaimPage.tsx
- packages/frontapp/src/app/pages/HomePage.tsx
- packages/frontapp/src/app/pages/SettingsPage.tsx
- tsconfig.base.json
> [314] Book claim history

- packages/frontapp/src/app/components/ClaimTable/index.tsx
> [fix/333]: Tab buttons should use pointer cursor

- packages/frontapp/src/app/pages/BookPreview.tsx
- packages/localization/src/lib/resources.ts
> Fix bug with claim table

- packages/frontapp/src/app/components/BooksByCategory/index.tsx
- packages/frontapp/src/app/components/CategorySearch/index.tsx
- packages/frontapp/src/app/components/CheckBox/index.tsx
- packages/frontapp/src/app/components/DropdownLocation/index.tsx
- packages/frontapp/src/app/components/SearchModal/index.tsx
- packages/frontapp/src/app/pages/SearchPage.tsx
> Fix checkboxes UI; Fix filter UI (fix #395)

- packages/apollo-client/src/lib/links/errorLink.ts
- packages/frontapp/src/app/components/Dropdown/index.tsx
- packages/frontapp/src/app/components/DropdownLocation/index.tsx
Location Dropdown arrow changed, window does not reload if the error occured
> Fix location dropdown arrow 

- package-lock.json
- package.json
- packages/frontapp/jest.config.js
- packages/frontapp/src/app/components/BookCard/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/BookCard/index.spec.tsx
- packages/frontapp/src/app/components/ClaimTable/Item.spec.tsx
- packages/frontapp/src/app/components/ClaimTable/Item.tsx
- packages/frontapp/src/app/components/SearchSuggestions/index.spec.tsx
- packages/frontapp/src/helpers/customRender.tsx
> add custom render function, emotion config (fix #421)

- packages/frontapp/src/app/components/BookInfo/index.tsx
- packages/frontapp/src/app/components/Dropdown/index.spec.tsx
- packages/frontapp/src/app/components/Dropdown/index.stories.tsx
- packages/frontapp/src/app/components/Dropdown/index.tsx
> feat: Closable dropdown; Default value; (close #425)

- packages/apiserver/src/resources/materials/material.resolver.ts
- packages/apollo-client/src/lib/generated/client-types.ts
- packages/apollo-client/src/lib/instance.ts
- packages/apollo-client/src/lib/queries/getItemById.gql
- packages/frontapp/index.d.ts
- packages/frontapp/src/app/components/BookInfo/DescriptionBook.spec.tsx
- packages/frontapp/src/app/components/BookInfo/DescriptionBook.tsx
- packages/frontapp/src/app/components/BookInfo/__snapshots__/DescriptionBook.spec.tsx.snap
- packages/frontapp/src/app/components/BookInfo/index.tsx
- packages/frontapp/src/app/components/ClaimTable/index.tsx
- packages/frontapp/src/app/components/DonateInfo/index.tsx
- packages/frontapp/src/app/globalUI/Table/index.tsx
- packages/frontapp/src/app/pages/BookPreview.tsx
- packages/frontapp/src/app/store/migrations/index.spec.js
> Fix #407/adjust item details screen to match design

- packages/frontapp/src/app/components/BookCard/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/BookCard/index.tsx
- packages/frontapp/src/app/components/BookCardExtended/__snapshots__/data.json
- packages/frontapp/src/app/components/BookCardExtended/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/BookCardExtended/index.spec.tsx
- packages/frontapp/src/app/components/BookCardExtended/index.tsx
- packages/frontapp/src/app/components/ClaimTable/index.tsx
- packages/frontapp/src/app/components/UserList/SingleUser.spec.tsx
- packages/frontapp/src/app/components/UserList/SingleUser.tsx
- packages/frontapp/src/app/components/UserList/__snapshots__/SingleUser.spec.tsx.snap
- packages/frontapp/src/app/models/helperFunctions/claimHistory.ts
- packages/frontapp/src/app/store/migrations/index.spec.js
- packages/frontapp/src/custom.d.ts
> Fix #394/adjust new cards effects

- packages/frontapp/src/app/components/ManagerInfoCard/index.spec.tsx
- packages/frontapp/src/app/components/ManagerInfoCard/index.tsx
- packages/frontapp/src/app/pages/HomePage.tsx
> fix_#437/Misaligned items on admin's main page

- packages/frontapp/src/app/components/BookCard/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/BookCard/index.tsx
- packages/frontapp/src/app/components/BookCardExtended/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/BookCardExtended/index.tsx
- packages/frontapp/src/app/components/ListAllItems/index.tsx
- packages/frontapp/src/app/components/UserList/SingleUser.tsx
- packages/frontapp/src/app/components/UserList/__snapshots__/SingleUser.spec.tsx.snap
> fix #436 Card shadows should match the design

- README.md
1. Updated `README.md` file to provide full step-by-step info how to run project locally as well as changed `docker-compose` config info to use an existing env file to run db
> Update info how to run project locally

- packages/frontapp/src/app/pages/HomePage.tsx
> New User Notifications panel should have gap at the bottom #397

- packages/apiserver/src/resources/notifications/notification.resolver.ts
- packages/apiserver/src/resources/notifications/notification.schema.graphql
- packages/apollo-client/src/graphql.schema.json
- packages/apollo-client/src/lib/generated/client-types.ts
- packages/apollo-client/src/lib/mutations/createSimpleNotification.gql
- packages/frontapp/src/app/components/AnswerToUser/index.tsx
- packages/frontapp/src/app/components/BookCardExtended/__snapshots__/data.json
- packages/frontapp/src/app/components/BookInfo/index.tsx
- packages/frontapp/src/app/components/UserCard/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/UserCard/index.spec.tsx
- packages/frontapp/src/app/components/UserCard/index.tsx
- packages/frontapp/src/helpers/tests/nextTick.ts
- packages/global-types/src/lib/global-types.ts
- packages/localization/src/lib/resources.ts
> Admin -> User notifications should work #399

- packages/frontapp/src/app/components/BooksByCategory/bookList.tsx
> show all the books when filters are empty (fix #463)

- packages/frontapp/src/app/components/Search/index.tsx
> Should not cut the search placeholder #464

- packages/frontapp/src/app/components/Modal/index.tsx
- packages/frontapp/src/app/components/StatisticsModal/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/StatisticsModal/index.spec.tsx
- packages/frontapp/src/app/components/StatisticsModal/index.tsx
- packages/frontapp/src/app/pages/HomePage.tsx
- packages/frontapp/src/helpers/customRender.tsx
- packages/localization/src/lib/resources.ts
> Library statistics should work #402

- packages/frontapp/src/app/components/MainComponent/index.tsx
- packages/frontapp/src/app/pages/DonatesFromUser.tsx
> fix menu on donates from user (fix #460)

- packages/frontapp/src/app/components/LabeledCheckbox/index.spec.tsx
- packages/frontapp/src/app/components/LabeledCheckbox/index.stories.tsx
- packages/frontapp/src/app/components/LabeledCheckbox/index.tsx
- packages/frontapp/src/app/components/LocationsContainer/index.tsx
- packages/frontapp/src/app/components/RadioButton/index.spec.tsx
- packages/frontapp/src/app/components/RadioButton/index.stories.tsx
- packages/frontapp/src/app/components/RadioButton/index.tsx
- packages/frontapp/src/app/pages/SettingsPage.tsx
> Adjust user settings page #459

- packages/frontapp/src/app/components/CategoriesList/index.tsx
- packages/localization/src/lib/resources.ts
> fix: rename label (close #474)

- packages/metadata-service/src/readers/abebooks.service/index.ts
- packages/metadata-service/src/readers/reader.service.ts
- packages/metadata-service/src/readers/readers.modules.ts
> add abebookservice for metadata

- packages/frontapp/src/app/components/BooksByCategory/bookList.tsx
- packages/frontapp/src/app/components/BooksByCategory/index.tsx
- packages/frontapp/src/app/components/CategoriesList/index.tsx
- packages/frontapp/src/app/components/ItemsNotFound/index.tsx
- packages/frontapp/src/app/pages/SearchPage.tsx
- packages/localization/src/lib/resources.ts
> Category search shows no result

- packages/frontapp/src/app/components/Header/index.tsx
- packages/frontapp/src/app/components/Navbar/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/Navbar/index.tsx
- packages/frontapp/src/app/components/NavbarItem/index.tsx
- packages/frontapp/src/app/components/Sidebar/index.tsx
> Adjust menu items

- packages/frontapp/src/app/components/DonateBookFlow/index.tsx
- packages/frontapp/src/app/components/DonateViaISBN/index.tsx
- packages/frontapp/src/app/components/MainComponent/index.tsx
- packages/localization/src/lib/resources.ts
Closes #484 
I left the white background for buttons because it's part of a form so no need to add more DOM node
> Donate item isbn mobile

- packages/frontapp/src/app/components/ManagerInfoCard/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/ManagerInfoCard/index.tsx
> Fix the postion of the `add item` button

- packages/frontapp/src/app/components/BooksByCategory/index.tsx
- packages/frontapp/src/app/components/Loader/index.tsx
- packages/frontapp/src/app/components/UserCard/index.spec.tsx
- packages/frontapp/src/app/components/UserCard/index.tsx
- packages/frontapp/src/app/components/UserList/index.tsx
- packages/frontapp/src/app/pages/BookPreview.tsx
- packages/frontapp/src/app/pages/SearchPage.tsx
> feat: replace "Loading..." with Loader component

- packages/frontapp/src/app/components/BackButton/index.tsx
- packages/frontapp/src/app/components/BooksByCategory/tags.tsx
> adjust search filters

- packages/frontapp/src/app/components/SearchByBookOrAuthor/index.tsx
- packages/frontapp/src/app/pages/DonatesFromUser.tsx
> make placeholder change lang immediately

- packages/frontapp/src/app/components/BackButton/index.tsx
- packages/frontapp/src/app/components/OverdueList/index.tsx
> fix 'GoBack' button margin

- packages/frontapp/src/app/components/BackButton/index.tsx
close #499 
Used window history state method to check if the current state is not equal to 0. 
If it's equal to 0 'BackButton' navigates to search page.
> make 'BackButton' to navigate to search when visited for the first time

- packages/frontapp/src/app/components/CategorySearch/index.tsx
- packages/frontapp/src/app/components/LabeledCheckbox/index.spec.tsx
- packages/frontapp/src/app/components/LabeledCheckbox/index.stories.tsx
- packages/frontapp/src/app/components/LabeledCheckbox/index.tsx
- packages/frontapp/src/app/components/LocationsContainer/index.tsx
- packages/frontapp/src/app/components/SearchFiltersForm/index.spec.tsx
- packages/frontapp/src/app/components/SearchFiltersForm/index.tsx
- packages/frontapp/src/app/components/SearchModal/index.tsx
- packages/frontapp/src/app/components/UserSearch/index.tsx
- packages/frontapp/src/app/hooks/useFilters.ts
- packages/frontapp/src/app/models/helperFunctions/filters.ts
- packages/frontapp/src/app/types/filterTypes.ts
- packages/localization/src/lib/resources.ts
> Search filter Refactoring

- packages/frontapp/src/app/components/AnswerToUser/index.tsx
- packages/frontapp/src/app/components/AskManagerForm/index.tsx
- packages/frontapp/src/app/components/ClaimOperation/index.tsx
- packages/frontapp/src/app/components/ErrorMessge/index.tsx
- packages/frontapp/src/app/components/SearchFiltersForm/index.tsx
- packages/frontapp/src/app/components/StatisticsModal/index.tsx
close #500 
Search Filter button
Library stats button
Block User button
Claim book button
Ask manager button
> reorder buttons in modals

- packages/frontapp/src/app/components/BooksByCategory/bookList.tsx
- packages/frontapp/src/app/components/BooksByCategory/index.spec.tsx
- packages/frontapp/src/app/components/BooksByCategory/tags.tsx
- packages/frontapp/src/app/components/SearchByUserName/index.tsx
- packages/frontapp/src/app/components/SearchWrapper/index.tsx
- packages/frontapp/src/app/components/UserList/index.tsx
> Readers search filters

- packages/apiserver/src/resources/messages/message.resolver.ts
- packages/apiserver/src/resources/messages/message.schema.graphql
- packages/apollo-client/src/graphql.schema.json
- packages/apollo-client/src/lib/generated/client-types.ts
- packages/apollo-client/src/lib/queries/getAllMessages.gql
- packages/frontapp/src/app/components/MainComponent/index.tsx
- packages/frontapp/src/app/components/ManagerInfoCard/index.tsx
- packages/frontapp/src/app/components/NotificationIcon/index.tsx
- packages/frontapp/src/app/components/Sidebar/index.tsx
- packages/frontapp/src/app/pages/HomePage.tsx
- packages/frontapp/src/app/pages/NotificationPage.tsx
- packages/frontapp/src/utils/routes.ts
- packages/global-types/src/lib/global-types.ts
> Manager notification with multiple locations

- packages/frontapp/src/app/components/Modal/index.tsx
- packages/frontapp/src/app/components/StatisticsModal/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/StatisticsModal/index.tsx
- packages/localization/src/lib/resources.ts
> refactor the modal window at the statistic page

- packages/frontapp/src/app/components/SearchWrapper/index.tsx
- packages/frontapp/src/app/components/StatisticsButton/index.tsx
- packages/frontapp/src/app/pages/HomePage.tsx
- packages/frontapp/src/assets/Vector.svg
closes #528 
There is no required SVG image in project library.
> add statistics button component

- packages/frontapp/src/app/components/AllBooksList/index.tsx
- packages/frontapp/src/app/components/BookCard/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/BookCard/index.tsx
- packages/frontapp/src/app/components/BookCardExtended/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/BookCardExtended/index.tsx
- packages/frontapp/src/app/components/BookInfo/DescriptionBook.tsx
- packages/frontapp/src/app/components/BookInfo/__snapshots__/DescriptionBook.spec.tsx.snap
- packages/frontapp/src/app/components/BookStatus/index.tsx
- packages/frontapp/src/app/components/ListAllItems/index.tsx
- packages/frontapp/src/app/globalUI/Status/index.tsx
> Adjust item card to match mobile ui

- packages/frontapp/src/app/components/Modal/index.tsx
- packages/frontapp/src/app/components/SearchFiltersForm/index.tsx
> Fix filter modal scrollability

- packages/frontapp/src/app/components/Modal/index.tsx
- packages/frontapp/src/app/components/SearchFiltersForm/index.tsx
- packages/frontapp/src/app/pages/StartPage.tsx
> Change modal bottom btns visibility

- packages/frontapp/src/app/components/MaterialSearch/index.tsx
> refactor filter window

- packages/apiserver/src/permission/grant.guard.ts
- packages/frontapp/src/app/components/UserCard/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/UserCard/index.tsx
- packages/frontapp/src/app/store/slices/userSlice.ts
We already have this functionality. To make it work just need to set GRANT_REVOKE_MANAGER to permissions column in person table.
- Improved error message;
- hid button if user doesn't have required permission.
Closes #585, Closes #582
> Fix Make user manager/reader functionality

- packages/frontapp/src/app/components/ClaimOperation/index.tsx
- packages/frontapp/src/app/components/DonateViaISBN/index.tsx
- packages/frontapp/src/app/components/MainComponent/index.tsx
- packages/frontapp/src/assets/AddBookBluePlus.svg
- packages/localization/src/lib/resources.ts
Closes #583 
- added `+` button on each manager page (except for `Add item` page)
- currently, button only redirect to the `Add item` page
- added localization fro isbn instructions
> Button on manager portal should work

- packages/frontapp/src/app/pages/HistoryOfClaimPage.tsx
- packages/frontapp/src/app/pages/HistoryOfDonatePage.tsx
> Remove second scrollbar from HoD & HoC pages

- packages/frontapp/src/app/components/BookCard/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/BookInfo/__snapshots__/DescriptionBook.spec.tsx.snap
- packages/frontapp/src/app/globalUI/Status/index.tsx
- packages/frontapp/src/app/hooks/useBookStatus.ts
- packages/ui-kit/src/lib/colors/index.ts
> Refactor return till label

- packages/frontapp/src/app/components/BookInfo/index.tsx
- packages/localization/src/lib/resources.ts
> Title with double braces rendered on Item page

- packages/frontapp/src/app/components/AnswerToUser/index.tsx
- packages/frontapp/src/app/components/ManagerInfoCard/index.tsx
- packages/frontapp/src/app/components/Notifications/index.tsx
- packages/frontapp/src/app/components/UserCard/index.tsx
- packages/localization/src/lib/resources.ts
> Fix item link on Home page & notifications overflow on Home page

- packages/frontapp/src/app/components/MainComponent/index.tsx
> Scan a code button overlaps statistics button on desktop

- packages/apiserver/src/migrations/1676528611145-addStatusEffectiveTo.ts
- packages/apiserver/src/resources/statuses/status.entity.ts
- packages/apiserver/src/resources/statuses/status.resolver.ts
- packages/apiserver/src/resources/statuses/status.service.ts
- packages/apiserver/src/resources/statuses/status.subscriber.ts
- Created migration to dd effective_to column to status table and populate it
- Updated afterInsert method to set correct effective_to date when adding new status
- Updated queries for retrieving overdue statuses
Closes #571
> Improve status table design #571

- package-lock.json
- package.json
- packages/frontapp/src/app/components/AllBooksList/index.tsx
- packages/frontapp/src/app/components/BookInfo/index.tsx
- packages/frontapp/src/app/components/CarouselWrapper/ControlPanel.tsx
- packages/frontapp/src/app/components/CarouselWrapper/SliderButtons.tsx
- packages/frontapp/src/app/components/CarouselWrapper/index.stories.tsx
- packages/frontapp/src/app/components/CarouselWrapper/index.tsx
- packages/frontapp/src/app/components/MainComponent/index.tsx
- packages/frontapp/src/app/pages/BookPreview.tsx
- packages/frontapp/src/app/pages/SearchPage.tsx
- packages/localization/src/lib/resources.ts
- packages/ui-kit/src/lib/colors/index.ts
Closes #606 
- ### Reader search page
- ### Readed item page
- Added story for `Carousel` component
- Small localization fixes
- Refactored `AllBookList` component
> Carousel buttons doesnt work

- packages/frontapp/src/app/components/BookInfo/ControlButtons.tsx
- packages/frontapp/src/app/components/BookInfo/EditButtons.tsx
- packages/frontapp/src/app/components/BookInfo/NotifyMeButtons.tsx
- packages/frontapp/src/app/components/BookInfo/index.tsx
- packages/localization/src/lib/resources.ts
Closes #631 
- checked on ios virtual machine as well, looks fine
- added localization to items buttons
> Fix item buttons width on mobile screens

- packages/frontapp/src/app/components/BookCard/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/BookCard/index.tsx
- packages/frontapp/src/app/components/BookCardExtended/__snapshots__/index.spec.tsx.snap
- packages/frontapp/src/app/components/BookCardExtended/index.tsx
- packages/frontapp/src/app/components/ManagerInfoCard/index.tsx
> Make books cards work as links
